version: "3.9"

services:
  battleMarket:
    image: node:16-alpine
    working_dir: /home/node/app
    
    volumes:
      - ./:/home/node/app
    command: "node ./App/battleMarket.js"
    restart: unless-stopped